services:
  api:
    container_name: kitkat-api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    environment:
      - DB_HOST=database
      - DB_PORT=${DATABASE_PORT}
      - DB_NAME=${DATABASE_DB}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - database

  database:
    container_name: postgres-db
    image: postgres:15
    restart: always
    ports:
      - "${POSTGRES_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - database

volumes:
  db_data:
