services:
  api:
    container_name: kitkat-api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET=${SECRET}
      - ISSUER=${ISSUER}
      - AUDIENCE=${AUDIENCE}
      - REALM=${REALM}
    depends_on:
      - database

  database:
    container_name: postgres-db
    image: postgres:15
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    depends_on:
      - database

volumes:
  db_data:
